#!/usr/bin/env bash

test_user="testuser"
src_path="$(realpath "$0")"
src_dir="$(dirname "$src_path")"
git_root="$(git rev-parse --show-toplevel)"

test_dir="tests/python/knot_resolver"
ignore="$test_dir/utils/modeling/types/path_testing"

if [ -z "${SWITCHED_USER:-}" ]; then

  # prepare permissions
  bash $test_dir/utils/modeling/types/prepare_path_testing

  if [ "$(id -u)" -eq 0 ]; then
    # add a test user if does not already exist
    if ! id "$test_user" >/dev/null 2>&1; then
      # only works on Debian
      adduser --disabled-password --gecos "" "$test_user"
    fi
    chown -R $test_user:$test_user $git_root
    exec su -m "$test_user" -c "SWITCHED_USER=1 $0"
  fi
fi

# ensure consistent behaviour
source $src_dir/utils/_env.sh

# run pytest
env PYTHONPATH=. pytest --junitxml=unit.junit.xml --cov=python/knot_resolver --show-capture=all --ignore=$ignore $test_dir
